# ======================================
# Faasera Documentation Configuration
# ======================================

title: Faasera Documentation
author: Faasera Inc.

# Navbar links (optional custom categories)
navbar-links:
  Overview: "faasera-product-overview"
  Architecture & Deployment:
    - System Architecture: "faasera-system-architecture"
    - Deployment Guide: "faasera-deployment-guide"
  User Guides:
    - Profiling Guide: "user-guide-profiler"
    - Masking Guide: "user-guide-masking"
    - Synthetic Data: "user-guide-synthetic"
    - Validation: "user-guide-validation"
    - Transformation: "user-guide-transformation"
  Implementation:
    - SDK Integration: "implementation-sdk"
    - API Integration: "implementation-api"
    - Cloud Functions: "implementation-cloud"
  Reference Docs:
    - Recognizer Types: "reference-recognizers"
    - Masking Functions: "reference-masking-functions"
    - Policy Format: "reference-policy-format"
  Compliance:
    - Regulation Coverage: "compliance-coverage"
    - Data Security: "compliance-security"

# Branding logo (hosted or local relative to /docs)
title-img: /assets/faasera-logo.png

# Socials and support
social-network-links:
  email: "support@faasera.ai"
  youtube: "https://www.youtube.com/@FaaseraAI"
  linkedin: "https://www.linkedin.com/company/faasera-ai"
  facebook: "https://www.facebook.com/faaseraAi"

# General Settings
rss-description: "Faasera is an AI-powered Function-as-a-Service platform for real-time data compliance, profiling, and synthetic data generation."

share-links-active:
  twitter: true
  linkedin: true
  facebook: false

url-pretty: "faasera.ai"
title-on-all-pages: true
feed_show_excerpt: true
feed_show_tags: false
post_search: false
edit_page_button: false

# Theme and colors
page-col: "#ffffff"
text-col: "#333333"
link-col: "#007acc"
hover-col: "#005f99"
navbar-col: "#ffffff"
navbar-text-col: "#333333"
footer-col: "#f5f5f5"
footer-text-col: "#666666"
footer-link-col: "#007acc"

# Jekyll / Build config
timezone: "Australia/Melbourne"
markdown: kramdown
highlighter: rouge
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - scripts/
  - .gitignore

plugins:
  - jekyll-paginate
  - jekyll-sitemap
